# Generated by Django 5.1.4 on 2024-12-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img', models.CharField(max_length=255)),
                ('quantity_purchased', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('food', 'Еда'), ('gift_set', 'Подарочный набор')], default='food', max_length=20)),
                ('for_who', models.CharField(choices=[('woman', 'Девушка'), ('man', 'Парень'), ('mom', 'Мама'), ('dad', 'Папа')], default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
