# Generated by Django 5.1.4 on 2024-12-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ozon_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Ozon'),
        ),
        migrations.AddField(
            model_name='product',
            name='wildberries_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Wildberries'),
        ),
        migrations.AddField(
            model_name='product',
            name='yandex_market_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Яндекс Маркет'),
        ),
    ]
