# Generated by Django 5.1.4 on 2024-12-28 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ozon_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ozon_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Ozon'),
        ),
        migrations.AddField(
            model_name='product',
            name='wildberries_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wildberries_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Wildberries'),
        ),
        migrations.AddField(
            model_name='product',
            name='yandex_market_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='yandex_market_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Яндекс Маркет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='for_who',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('is_main', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product')),
            ],
        ),
    ]
